#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

# Define some colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Get public IP address
IP_ADDRESS=$(curl -s ifconfig.me)

# Update and upgrade
apt-get update -y
apt-get upgrade -y

# Install nginx and zip
apt-get install -y nginx zip

# Create directories
mkdir -p /etc/nginx/cert
mkdir -p /var/www/html/.well-known/pki-validation

# Configure firewall
ufw allow 'Nginx Full'
ufw allow OpenSSH
echo "y" | ufw enable

# Configure nginx
cat << EOF > /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
#    listen 443 ssl default_server;
#    listen [::]:443 ssl default_server;
#    ssl_certificate /etc/nginx/cert/certificate.crt;
#    ssl_certificate_key /etc/nginx/cert/private.key;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name $IP_ADDRESS;
#    if (\$scheme = http) {
#        return 301 https://\$server_name\$request_uri;
#    }

    location / {

    }
}
EOF

# Restart nginx
service nginx restart

# Print message
echo -e "${RED}*N*O*T*E*S*${NC} remove # in ${GREEN}/etc/nginx/sites-enabled/default${NC} after cerificate installed to run in full https"
echo ""
echo ""
